### ISSUE TITLE
vacancy_percentage need to use job skills

### ISSUE THREAD

**Issue by HoloborodkoBohdan** [HoloborodkoBohdan/work4sharingPy#6]
* percentage - процент соответствия вакансии
* must_have_skills - скилы, которые есть у сотрудника но нет в вакансии. 

Мы пытаемся использовать must_have_skills  как те, которые нужно сотруднику узнать, но он их и так знает.

```
def vacancy_percentage(employer_skills, vacancy_description):
    if (employer_skills == None):
        skills = set()
    else:
        skills = set(employer_skills)
    shared = set()
    must_have_skills = set()
    for skill in skills:
        if vacancy_description.find(skill) == -1:
            must_have_skills.add(skill)
        else:
            shared.add(skill)

    # Percentage algorithm is worth reviewing
    if len(skills) == 0:
        percentage = 0
    else:
        percentage = int((len(shared) / len(skills)) * 100)
    return percentage, must_have_skills
```

Нужно к каждой вакансии подбирать необходимые скилы и сравнивать их с тем, что есть у сотрудника.

**Comment by znack2** [comment]
Верно!
Мое видение такое: 
1) в вакансии, которые мы собираем с HH, мы ищем ключевые слова.
(вероятнее всего они уже лежат в отдельном поле)
2) компания в профиле сотрудника в нашей системы, указывает скиллы своего сотрудника
(возможно загрузив его резюме из HH, возможно вручную)
3) система матчинга находит пересечения по скиллам, и обнаруживает ту вакансию и то резюме в котором совпадают например 80% скиллов. 
4) Тех скилов(ключевых слов), которых нехватает парсер отправляет на пхп бэк вместе с самой вакансией.
5) В кабинете компании на пхп, мы выводит каждому сотруднику на какие вакансии его могут взять, какой процент совпадения по скиллам и какие курсы ему нужно доизучать, чтобы его взяли.
6) ссылки на курсы берутся из базы данных курсов
(возможно надо находить по скилам из отдельно и парсить )
